name: Code Coverage

on: [push]

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: |
          pip install six
          python setup.py install
          pip install coverage
          coverage run --source=websocket --omit="/*/tests/__init__.py","*/tests/test_cookiejar.py","*/tests/test_websocket.py" websocket/tests/test_cookiejar.py
          coverage report
          coverage xml
      - name: Codecov
        uses: codecov/codecov-action@v1.2.1
