name: Linting with flake8

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Perform flake8 linting
        run: |
          pip install flake8
          flake8 --version
          flake8 . --exit-zero --statistics
